---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fluent-AgentLite
no_index:
  directory:
    - inc
    - t
requires:
  Data::MessagePack: 0.35_01
  JSON::XS: 0
  Log::Minimal: 0
  Time::HiRes: 0
  Time::Piece: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.8
